---
title: "GLP Shrables"
output: html_document
---

<style type="text/css">
h1 {
  text-align: center;
}
h1,h2,h3,h4,h5,h6 {
  font-family: "Museo Sans 300";
}
body{
  font-family: "Museo Sans 300";
  font-size: 15px;
}
</style>

```{r setup, message = FALSE, echo = FALSE}
library(tidyr)
library(readr)
library(dplyr)
library(stringr)
library(magrittr)
library(glptools)

library(purrr)
library(leaflet)
```

```{r, message = FALSE, echo = FALSE}
make_map <- function(maps, var,
                     hover_name, legend_title,
                     year = "", race = "total", sex = "total",
                     units = "Percent",
                     color_style = "sequential", palette = "", reverse_pal = F,
                     continuous = T, var_bins,
                     tiles = T,
                     bold_nh = T,
                     save_file = "", save_image = ""){
  
  if(typeof(maps) != "list") {maps <- list(maps)}

  # Get type of maps
  geographies <- map_chr(maps, df_type)
  
  # Filter data frames to relevant 
  filter_fxn <-  function(obj, year, sex, race) {
    if ("year" %in% names(obj) & year == "") obj <- obj[obj$year == max(obj$year),]
    if ("race" %in% names(obj)) obj <- obj[obj$race == race,]
    if ("sex" %in% names(obj))  obj <- obj[obj$sex == sex,]
    
    obj
  }
  
  maps %<>% map(~filter_fxn(., year, sex, race))
  
  # Bind maps to map objects
  bind_fxn <- function(obj, geog) {

    if (geog == "tract") {
      map_tract <- glptools:::map_tract
      map_tract@data %<>% left_join(obj, by = "tract")
      return(map_tract)
    } else if (geog == "nh") {
      map_nh <- glptools:::map_nh
      map_nh@data %<>% left_join(obj, by = "neighborhood")
      return(map_nh)
    } else if (geog == "muw") {
      map_muw <- glptools:::map_muw
      map_muw@data %<>% left_join(obj, by = "neighborhood")
      return(map_muw)
    }
  }
  
  maps %<>% map2(geographies, bind_fxn)

  # Rename variable to "var"
  maps %<>% map(function(obj) {obj@data$var <- obj@data[[var]]; obj})

  #concatenate second or third line of text for tract labels using units parameter
  line_1_2_fxn <- function(obj, geog) {
    if (geog == "tract") {
      obj@data %<>%
        mutate(
          line1 = paste0("Tract ", name, " in the "),
          line2 = paste0(neighborhood, " neighborhood"))
    } else if (geog %in% c("nh", "muw")) {
      obj@data %<>%
        mutate(
          line1 = paste0(neighborhood, " neighborhood"))
    } else if (geog == "zip") {
      obj@data %<>%
        mutate(
          line1 = paste0("Zip code ", zip))
    }

    obj
  }

  maps %<>% map2(geographies, line_1_2_fxn)

  line3_fxn <- switch(units,
                      "Percent" = function(obj) {obj@data %<>% mutate(
                        line3 = paste0(hover_name, ": ", round(var, 2), "%")); obj},

                      "Dollars" = function(obj) {obj@data %<>% mutate(
                        line3 = paste0(hover_name, ": $", prettyNum(signif(var, 3),
                                                                    big.mark = ",",
                                                                    preserve.width = "none"))); obj},

                      "none" = function(obj) {obj@data %<>% mutate(
                        line3 = paste0(hover_name, ": ", round(var, 2))); obj},

                      function(obj) {obj@data %<>% mutate(
                        line3 = paste(hover_name, ": ", round(var, 2), " ", units)); obj})

  maps %<>% map(line3_fxn)

  #combine lines of text into full formatted label
  label_fxn <- function(obj) {

    if("line2" %in% names(obj@data)){
      labels <- sprintf("%s<br/>%s<br/>%s",
                        obj@data$line1,
                        obj@data$line2,
                        obj@data$line3) %>%
        lapply(htmltools::HTML)

      labels[[which(obj@data$neighborhood == "Airport")]] <-
        htmltools::HTML(sprintf("%s<br/>%s<br/>%s",
                                "Tract 98",
                                "Louisville International Airport",
                                "No residents"))
    } else {
      labels <- sprintf("%s<br/>%s",
                        obj@data$line1,
                        obj@data$line3) %>%
        lapply(htmltools::HTML)

      labels[[which(obj@data$neighborhood == "Airport")]] <-
        htmltools::HTML(sprintf("%s<br/>%s",
                                "Louisville International Airport",
                                "No residents"))
    }
    labels
  }

  labels <- map(maps, label_fxn)

  #Define palette using color_style parameter
  if (palette != "") {
    color_vector <- col_palette
  } else if (color_style %in% c("sequential", "Sequential")) {
    color_vector <- RColorBrewer::brewer.pal(9, "BuPu")
  } else if (color_style %in% c("divergent", "Divergent")) {
    color_vector <- RColorBrewer::brewer.pal(11, "RdYlGn")
  }

  if (reverse_pal) pal <- rev(pal)

  var_range <- map(maps, function(obj) range(obj@data$var, na.rm = T)) %>%
    range()

  if (continuous) {
    pal <- leaflet::colorNumeric(
      palette = color_vector,
      domain = var_range)
  } else {
    pal <- leaflet::colorBin(
      palette = color_vector,
      domain = var_range,
      bins = var_bins)
  }

  #Create map title using legend_title parameter
  title_text <- switch(units,
                       "Percent" = paste0(legend_title, " (%)"),
                       "Dollars" = paste0(legend_title, " ($)"),
                       "none"    = legend_title,
                       paste0(legend_title, " (", units, " )"))

  #create map
  geographies %<>% recode(tract = "Census Tracts", nh = "GLP Neighborhoods",
                          muw = "United Way Neighborhoods")

  m <- leaflet()

  for (i in 1:length(maps)) {
    this_map  <- maps[[i]]
    this_geog <- geographies[[i]]
    these_labels <- labels[[i]]

    m <- m %>% addPolygons(
      data = this_map,
      color = "#444444", weight = 1, smoothFactor = 0.5, opacity = 1.0, fillOpacity = 0.5,
      fillColor = ~pal(var),
      label = these_labels,
      labelOptions = labelOptions(
        style = list("font-weight" = "normal", "font-family" = "Arial", padding = "3px 8px"),
        textsize = "15px",
        direction = "auto"),
      group = this_geog)

    if (this_geog == "Census Tracts" & bold_nh & "nh" %in% geographies) {
      
      nh_map_id <- match("nh", geographies)
      
      m <- m %>% addPolygons(
        data = maps[[nh_map_id]],
        color = "#444444", weight = 2, smoothFactor = 0.5, opacity = 1.0, fill = FALSE,
        group = "tract")
    }
  }

  m <- m %>%
    addLegend(pal = pal, values = var_range, opacity = 0.7, title = title_text, position = "bottomright") %>%
    addLayersControl(baseGroups = geographies,
                     options = layersControlOptions(collapsed = F))

  #m <- m %>%
  #  hideGroup("GLP Neighborhoods") %>%
  #  showGroup("United Way Neighborhoods")

  if (tiles == TRUE) {
    m %<>% addTiles()
  } else if (tiles != FALSE) {
    m %<>% addTiles(urlTemplate = '//{s}.basemaps.cartocdn.com/rastertiles/voyager_nolabels/{z}/{x}/{y}.png')
  }

  # Fix legend NA value
  css_fix <- "div.info.legend.leaflet-control br {clear: both;}"
  html_fix <- htmltools::tags$style(type = "text/css", css_fix)
  m %<>% htmlwidgets::prependContent(html_fix)

  if (save_file != "") {
    rgdal::writeOGR(obj = map, dsn = save_file,
                    layer = map_obj, driver = "ESRI Shapefile",
                    overwrite_layer = TRUE)
  }
  if (save_image != "") {
    mapview::mapshot(m, file = save_image %p% ".pdf", zoom = 0.4)
  }

  m
}
```

```{r}
job_loss <- read_csv("output_data/job_loss_rate.csv", col_types = "cn")

process_map(job_loss, loss_rate, return_name = "job_loss", method = "mean") %>% 
  list2env(.GlobalEnv)

make_map(list(job_loss_tract, job_loss_nh, job_loss_muw), "loss_rate", "Job Loss", "Job Loss")
```





